{{ if .Values.configmap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-cm
  labels:
    {{- include "sharedlabels" . | nindent 4 }}
data:
{{ toYaml .Values.configmap | indent 2 }}


{{ end }}